#!/usr/bin/env bash
# Installs nginx web server and redirect to a link
# addittionally custom 404 page to contain a given string

apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page  " > /usr/share/nginx/html/404.html
sudo service nginx restart
