#!/usr/bin/env bash
#This script fulfills these Requirements:
#Install and configure HAproxy on your lb-01 server
#Configure HAproxy so that it send traffic to web-01 and web-02
#Distribute requests using a roundrobin algorithm
#Make sure that HAproxy can be managed via an init script
#Make sure that your servers are configured with the right hostnames: [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get install haproxy=2.8.\*

cat <<EOL >> /etc/haproxy/haproxy.cfg
frontend myfrontend
    bind *:80
    default_backend mybackend

backend mybackend
    balance roundrobin
    server 403994-web-01 54.159.22.249:80 check
    server 403994-web-02 54.173.9.57:80 check
EOL
service haproxy restart
