#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely
# Function to handle SIGTERM signal
handle_sigterm() {
    echo "I am invincible!!!"
}

# Register the handle_sigterm function to handle SIGTERM
trap 'handle_sigterm' SIGTERM
i=0
while [ $i -ge 0 ]; do
    echo "To infinity and beyond"
    sleep 2
done
