#!/usr/bin/env bash
# This Bash script configures an Ubuntu server with the below requirements.

# Requirements:
#	localhost resolves to 127.0.0.2
#	facebook.com resolves to 8.8.8.8.
sudo cp /etc/hosts ~/hosts.new
sudo sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
echo "8.8.8.8 facebook.com" | sudo tee -a ~/hosts.new > /dev/null
sudo cp -f ~/hosts.new /etc/hosts
