#!/usr/bin/env bash

# This Bash script that accepts one argument
# the script should run the whoami command under the user passed as an argument
if [ -z "$1" ]; then
  exit 1
fi

sudo -u "$1" whoami
